### PR TITLE
Ensure getMonth() is incremented before padding result

### LINKED ISSUE #1: Wrong output for a month
Hi,

You forget to add +1 for a month.

``` js
console.log(timestamp('YYYY-MM-DD HH:mm:ss'));
// 2015-09-16 20:48:16
```

It should be `2015-10-16 20:48:16` ;)

### PR DESCRIPTION
**Pull request by evocateur**
This fixes #1

### CODE REVIEW

**Comment by evocateur** [comment]
This would be a prerequisite for js-cli/fancy-log/pull/3 to be accepted, I would think.

**Comment by jonschlinkert** [comment]
Thank you, I really appreciate it.

**Comment by evocateur** [comment]
Glad I could help!

**Comment by jonschlinkert** [comment]
tagged and published to npm as 0.1.3. thanks again!

**Pull request merged**
