### PR TITLE
add exports.default

### PR DESCRIPTION
**Pull request by luckydrq**
add exports.default to resolve typescript import(https://github.com/jonschlinkert/time-stamp/issues/14)

### CODE REVIEW

**Comment by luckydrq** [comment]
Reason: https://github.com/jonschlinkert/time-stamp/pull/18#issuecomment-732671198

**Comment by fregante** [comment]
This is just a patch for incorrect underlying code. This only works because for years bundlers have tried to shoehorn ESM into CJS concepts, but the 2 are not equivalent. 

If the module is CJS it should not use `export default`.

#18 is the correct way.

**Comment by luckydrq** [comment]
> This is just a patch for incorrect underlying code. This only works because for years bundlers have tried to shoehorn ESM into CJS concepts, but the 2 are not equivalent.
> 
> If the module is CJS it should not use `export default`.
> 
> #18 is the correct way.

All right. 
Either adding `exports.default` for the module or using `export =` in declaration is good to me. So when will https://github.com/jonschlinkert/time-stamp/pull/18 get merged?

**Comment by luckydrq** [comment]
ping @jonschlinkert

**Pull request closed without merging**
