### PR TITLE
Feature/use utc

### PR DESCRIPTION
**Pull request by mvanroon**
Let's switch to UTC so that we don't have to deal with timezones

### CODE REVIEW

**Comment by jonschlinkert** [comment]
I'm okay with this, @doowb? 

edit: just remembered this is also used in `fancy-log`. @phated any objections to this? I can't think of any drawbacks but would like your opinion.

**Comment by doowb** [comment]
I think I'm okay with this mainly because I'm used to seeing UTC times when running tasks on remote servers and in logs.

Maybe we can take an option or expose another method that uses the UTC methods. Then implementors can choose to use UTC or local timezones.

**Comment by mvanroon** [comment]
Should it use UTC by default?

**Comment by phated** [comment]
Implement as new method so it can be a non-breaking change.  Further down the road, we can revisit moving it into the default export.

**Comment by mvanroon** [comment]
Sorry for the late reply.

I'd prefer a separate method, but we can't do that without changing the module exports. So I went with a optional third argument instead. The second argument (the date) may still be omitted.

**Comment by phated** [comment]
> I'd prefer a separate method, but we can't do that without changing the module exports. 

huh? you can just attach a property

**Comment by mvanroon** [comment]
You mean export an object instead of a function? That would break things.

**Comment by phated** [comment]
No, a function is an object.

```js
module.exports = myDefaultFunc;
module.exports.utc = myUtcFunc;
```

**Comment by mvanroon** [comment]
Gotcha. Updated.

**Comment by doowb** [comment]
@mvanroon will you rebase the changes in this PR. I accidentally merged another PR which is causing a conflict. Also, we'll handle updating the version in `package.json` after merging. Thanks!

**Comment by mvanroon** [comment]
I am having trouble with finding a way to add the utc export as a helper in the .verb.md file, so I wasn't able to update the README with utc examples

**Comment by doowb** [comment]
That's fine, thanks for the update!

**Pull request merged**
